// <auto-generated />
namespace TheMasterProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LeadMember_Relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeadMember_Relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071129024_LeadMember_Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
